Task 2
NadyaKir/react-course pull request #2
Opened 2023-06-11 11:45 UTC by NadyaKir

Added functionality: checkbox change card styles.

2023-06-11 19:27 UTC, Jaskon commented
In this PR you have changes from task-2 and task-1. Could you please only show here task-2 changes?
(You need to merge task-1 into task-2)

2023-06-12 08:25 UTC, NadyaKir commented
> In this PR you have changes from task-2 and task-1. Could you please only show here task-2 changes? (You need to merge task-1 into task-2)

Done

2023-06-13 14:23 UTC, Jaskon requested changes

2023-06-13 14:23 UTC, Jaskon commented on src/components/Card/Card.js
> +//god help push this branch
Remove this please :)

2023-06-13 15:35 UTC, NadyaKir commented on src/components/Card/Card.js
> +//god help push this branch
Okay))

2023-06-14 09:53 UTC, Jaskon approved these changes

2023-06-14 12:13 UTC, merged