Task 6
NadyaKir/react-course pull request #6
Opened 2023-08-02 09:35 UTC by NadyaKir

Разбить структуру директорий проекта на подобии последних двух уроков (директории components).
Разбить компонент “Card” по крайней мере на 2 компонента (CardHeader и CardBody).
(Т.е. структура должна быть
-Card
-CardHeader
-CardBody
)
Создать общий компонент “CardList”, который должен отрисовывать компоненты “Card”. Добавить компонент “CardList” на страницу (он должен отрисовать ваши карточки (т.е. заменить функционал, который отрисовывает карточки сейчас))
Добавить кнопку “Удалить выбранные карточки”.
При нажатии на кнопку “Удалить выбранные карточки”, выбранные карточки (чекбоксом) должны удаляться.

2023-08-02 15:42 UTC, Jaskon requested changes

2023-08-02 15:42 UTC, Jaskon commented on src/components/Card/Card.js
> +    }
Could you try to do deletion functionality without creating a `selectedCardIds` state?

2023-08-03 15:40 UTC, NadyaKir commented on src/components/Card/Card.js
> +    }
Done

2023-08-04 11:21 UTC, Jaskon approved these changes

2023-08-04 12:33 UTC, merged